name: Node.js CI and Deploy

on:
    push:
        branches: ['master']

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x] # Adjust as needed

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm install

            - name: build-prod
              if: github.ref == 'refs/heads/master'
              run: npm run build-production

            - name: Install sshpass
              run: sudo apt-get update && sudo apt-get install -y sshpass

            - name: Remove old build artifacts
              run: |
                  sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_IP }} 'sudo rm -rf /var/www/game-client/*'

            - name: Transfer Build Artifacts
              run: |
                  sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp -o StrictHostKeyChecking=no -r dist/* ${{ secrets.SERVER_IP }}:/var/www/game-client
